apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-ticketing-app
  namespace: event-ticketing
  labels:
    app: event-ticketing-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-ticketing-app
  template:
    metadata:
      labels:
        app: event-ticketing-app
    spec:
      containers:
      - name: event-ticketing-app
        image: event-ticketing:latest
        ports:
        - containerPort: 8080
        env:
        # Stripe Configuration - Commented out for now
        # - name: STRIPE_SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: event-ticketing-secret
        #       key: stripe-secret-key
        # - name: STRIPE_PUBLISHABLE_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: event-ticketing-secret
        #       key: stripe-publishable-key
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: event-ticketing-config 